### PR TITLE
cope with th/rd/st in roc date

### PR DESCRIPTION
**Pull request by jnicho02**

### CODE REVIEW

**Comment by zathras777** [comment]
Good catch. How about we simply remove any offending suffixes? 

Something akin to

pattern = re.compile('(st|nd|rd|th|,)')
...
dtt = datetime.strptime(pattern.sub('', row_data[0].text.strip()), "%d %B %Y").date()

**Comment by jnicho02** [comment]
have to be careful not to strip the 'st' in 'August'

**Comment by mtoftum** [comment]
How about outsourcing the work to another module?:

>>> import parsedatetime
>>> cal = parsedatetime.Calendar()
>>> cal.parse('27th October 2016')
(time.struct_time(tm_year=2016, tm_mon=10, tm_mday=27, tm_hour=15, tm_min=59, tm_sec=28, tm_wday=0, tm_yday=305, tm_isdst=0), 1)
>>> cal.parse('27 October 2016')
(time.struct_time(tm_year=2016, tm_mon=10, tm_mday=27, tm_hour=15, tm_min=59, tm_sec=39, tm_wday=0, tm_yday=305, tm_isdst=0), 1)

**Comment by zathras777** [comment]
Good point about August. It's unusual to have full months rather than the usual 3 or 4 chars :-)

**Pull request merged**
